service: service-c

package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128
  stage: local
  region: localhost
  profile: default

functions: ${file(./functions.yml)}
